version: "3.9"

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    image: streamlit
    container_name: streamlit
    command: streamlit run overview.py server.port=8501 --server.address=0.0.0.0
    volumes:
      - ..:/usr/src
    ports:
      - "8501:8501"